name: Add new issue/PR to project

on:
  issues:
    types:
      - opened
      - reopened

  pull_request_target:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issue or PR to project
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: add-to-project
        uses: ./
        with:
          avocado-project: true
